apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openshift-acme.fullname" . }}
  labels:
    {{- include "openshift-acme.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "openshift-acme.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "openshift-acme.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "openshift-acme.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.controller.repository }}:{{ .Values.image.controller.tag }}"
          imagePullPolicy: {{ .Values.image.controller.pullPolicy }}
          args:
            - --exposer-image={{ .Values.image.exposer.repository }}:{{ .Values.image.exposer.tag }}
            - --loglevel={{ .Values.acme.loglevel }}
          {{- if .Values.acme.singleNamespace }}
            - --namespace=$(CURRENT_NAMESPACE)
          env:
            - name: CURRENT_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
