{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
{{- if .Values.acme.singleNamespace }}
kind: Role
{{- else }}
kind: ClusterRole
{{- end }}
metadata:
  name: {{ include "openshift-acme.fullname" . }}
  labels:
    {{- include "openshift-acme.labels" . | nindent 4 }}
rules:
- apiGroups:
  - "route.openshift.io"
  resources:
  - routes
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
  - deletecollection

- apiGroups:
  - "route.openshift.io"
  resources:
  - routes/custom-host
  verbs:
  - create

- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  - secrets
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete

- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - update
  - patch

- apiGroups:
  - ""
  resources:
  - limitranges
  verbs:
  - get
  - list
  - watch

- apiGroups:
  - "apps"
  resources:
  - replicasets
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
{{- end }}