{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
{{- if .Values.acme.singleNamespace }}
kind: RoleBinding
{{- else }}
kind: ClusterRoleBinding
{{- end }}
metadata:
  name: {{ include "openshift-acme.fullname" . }}
  labels:
    {{- include "openshift-acme.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "openshift-acme.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  {{- if .Values.acme.singleNamespace }}
  kind: Role
  {{- else }}
  kind: ClusterRole
  {{- end }}
  name: {{ include "openshift-acme.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
