{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "openshift-acme.serviceAccountName" . }}
  labels:
{{ include "openshift-acme.labels" . | nindent 4 }}
{{- end }}
