---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kube-descheduler.fullname" . }}
  labels:
    {{- include "kube-descheduler.labels" . | nindent 4 }}
data:
  policy.yaml: |
{{ .Values.policy | indent 4 }}