# Default values for velero-pvc-watcher.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: bitsbeats/velero-pvc-watcher
  tag: "0.3.0"
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 2112

resources:
  limits:
    cpu: 750m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

metrics:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "2112"
    prometheus.io/path: "/metrics"

rbac:
  create: true

nodeSelector: {}
tolerations: []
affinity: {}
